BaseApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

OralExpertsSGCD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BaseApp.urls')),                     # index - homepage - dashboard principal
    path('pacientes/', include('PacientesApp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PacientesApp/urls.py
from django.urls import path
from . import views

app_name = 'pacientes'
urlpatterns = [
    # path('', views.index, name='index'),           #añadirle una pag principal a sample.com/pacientes/
    path('', views.listaPaciente, name='listaPaciente'),
    path('nuevo/', views.nuevoPaciente, name='nuevoPaciente'),
    path('<int:item_id>/perfil/', views.perfilPaciente, name='perfilPaciente'),

    # Especialidades
    path('<int:item_id>/odontogeneral', views.listaOdontogeneral, name='listaOdontogeneral'),
    path('<int:item_id>/odontogeneral/nuevo', views.nuevoOdontogeneral, name='nuevoOdontogeneral'),

    path('<int:item_id>/odontopediatria', views.listaOdontopediatria, name='listaOdontopedriatria'),
    path('<int:item_id>/odontopediatria/nuevo', views.nuevoOdontopediatria, name='nuevoOdontopediatria'),

    path('<int:item_id>/endodoncia', views.listaEndodoncia, name='listaEndodoncia'),
    path('<int:item_id>/endodoncia/nuevo', views.nuevoEndodoncia, name='nuevoEndodoncia'),

    path('<int:item_id>/ortodoncia', views.listaOrtodoncia, name='listaOrtodoncia'),
    path('<int:item_id>/ortodoncia/nuevo', views.nuevoOrtodoncia, name='nuevoOrtodoncia'),

    path('<int:item_id>/rehaboral', views.listaRehaboral, name='listaRehaboral'),
    path('<int:item_id>/rehaboral/nuevo', views.nuevoRehaboral, name='nuevoRehaboral'),

    # PlanDeTratamiento
    path('<int:item_id>/plantratamiento', views.planTratamiento, name='planTratamiento'),

    # pagos
    path('<int:item_id>/pagos', views.listaPagos, name='listaPagos'),
    path('<int:item_id>/pagos/nuevo', views.nuevoPago, name='nuevoPago'),

    # recetas
    path('<int:item_id>/recetas', views.listaRecetas, name='listaRecetas'),

    # imagenes
    path('<int:item_id>/imagenes', views.imagenes, name='imagenes'),

    # odontograma
    path('<int:item_id>/odontograma', views.odontograma, name='odontograma'),
    path('<int:item_id>/odontograma/actualizar', views.actualizaOdontograma, name='actualizaOdontograma')
]

templates/base.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <title>Plataforma OralExperts {% block titulo %}{% endblock %}</title>

        <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
        <!-- css estilos -->
        <!-- fuente -->
        <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/nunito/stylesheet.css' %}">
        <!-- bootstrap datatables -->
        <link rel="stylesheet" href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}">
        <!-- sb-admin -->
        <link rel="stylesheet" href="{% static 'css/sb-admin-2.css' %}">
        <!-- estilos personalizados -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        {% block extrahead %}
        {% endblock extrahead %}
    </head>
    <style>
        .fa, .fab, .fad, .fal, .far, .fas {
       
        line-height: 1.5;
        }
        .text-primary {
            color: #007cba !important;
        }
        .btn-info:not(:disabled):not(.disabled):active, .btn-info:not(:disabled):not(.disabled).active, .show > .btn-info.dropdown-toggle {
         color: #fff;

         border-color: #007cba;
        }
    </style>
    <body id="page-top">
        <!-- Page Wrapper -->
         <div id="wrapper">
            <!--Menu-->
            <!-- Sidebar -->
            <ul class="navbar-nav  sidebar sidebar-dark accordion" id="accordionSidebar" style="background-color: #007cba;">

                <!--logo oralexperts menu-->
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'index' %}">
                    <!--<div class="sidebar-brand-icon rotate-n-15">-->
                    <div class="sidebar-brand-icon">
                        <img src="{% static 'img/diente.png' %}">
                    </div>
                    <div class="sidebar-brand-text mx-3"><img src="{% static 'img/logomin.png' %}" style="margin-left: -15px; margin-top: 4;"></div>
                </a>
                <!--logo oralexperts menu end-->
                <!-- Divider -->
                <hr class="sidebar-divider my-0">
                <!-- Divider -->
                <hr class="sidebar-divider">

                <!-- Heading -->
                <div class="sidebar-heading">
                    Historias Clinicas
                </div>

                <!-- App de pacientes -->
                <!-- Nav Item - Utilities Collapse Menu -->
                <li class="nav-item {% block inicio-activo %}{% endblock %}">
                    <a class="nav-link" href="{% url 'index' %}">
                    <i class="fas fa-fw fa-home"></i>
                    <span>inicio</span></a>
                </li>
                <li class="nav-item {% block registrar-activo %}{% endblock %}" >
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePacientes"
                        aria-expanded="true" aria-controls="collapsePacientes">
                        <i class="fas fa-fw fa-wrench"></i>
                        <span>Pacientes</span>
                    </a>
                    <div id="collapsePacientes" class="collapse" aria-labelledby="headingPacientes"
                        data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <a class="collapse-item" href="{% url 'pacientes:nuevoPaciente' %}">Agregar nuevo paciente</a>
                            <a class="collapse-item" href="{% url 'pacientes:listaPaciente' %}">Lista de pacientes</a>
                        </div>
                    </div>
                </li>

            

                <!-- App de citas -->
                <li class="nav-item">
                    <a class="nav-link" href="">
                        <i class="fas fa-fw fa-calendar"></i>
                        <span>Citas Médicas</span></a>
                </li>

                <!-- Divider -->
                <hr class="sidebar-divider">

                <!-- Heading -->
                <div class="sidebar-heading">
                    Administración Clinica 
                </div>

                <!--App Reportes-->
                <li class="nav-item">
                    <a class="nav-link" href="">
                        <i class="fas fa-fw fa-table"></i>
                        <span>Reportes</span></a>
                </li>
                <!--App de inventarios-->
                <li class="nav-item ">
                    <a class="nav-link" href="">
                        <i class="fas fa-fw fa-archive"></i>
                        <span>Inventario</span></a>
                </li>

                <!-- Divider -->
                <hr class="sidebar-divider d-none d-md-block">

                <!-- Sidebar Toggler (Sidebar) -->
                <div class="text-center d-none d-md-inline">
                    <button class="rounded-circle border-0" id="sidebarToggle"></button>
                </div>

                </ul>
                <!--Menu end-->
                <div id="content-wrapper" class="d-flex flex-column">
                     <div id="content">
                        <!--navbar user-->
                          <!-- Topbar -->
                        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                            <!-- Sidebar Toggle (Topbar) -->
                             <!-- Sidebar Toggle (Topbar) -->
                            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                                <i class="fa fa-bars"></i>
                            </button>
                            <!-- Topbar Navbar -->
                            <ul class="navbar-nav ml-auto">
                                <!-- Nav Item - User Information -->
                                <li class="nav-item dropdown no-arrow">
                                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">Dr. Dennery Gallegos</span>
                                        <img class="img-profile rounded-circle"
                                            src="{% static 'img/undraw_profile.svg' %}">
                                    </a>
                                    <!-- Dropdown - User Information -->
                                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                        aria-labelledby="userDropdown">    
                                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                            Cerrar Sesión
                                        </a>
                                    </div>
                                </li>

                            </ul>

                        </nav>
                              <!-- End of Topbar -->
                         <!--navbar user end-->
                          {% block body %}
                          {% endblock %}
                    </div>
                    <!-- Footer -->
                    <footer class="sticky-footer bg-white">
                        <div class="container my-auto">
                            <div class="copyright text-center my-auto">
                                <span>Copyright &copy; Oral Experts 2021</span>
                            </div>
                        </div>
                    </footer>
                    <!-- End of Footer -->
                </div>

         </div>
         <!-- Page Wrapper end-->
        
       
        <!-- javascript -->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
        <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
        <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>
        <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
        <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
        {% block extra_js %}{% endblock extra_js %}
        <!-- JS de los graficos -->
        <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script> 
        <!-- Page level custom scripts -->
        <script src="{% static 'js/demo/chart-area-demo.js' %}"></script> 
        <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script> 

        <!-- javascript end -->
    </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block titulo %} | Inicio{% endblock %}
{% load static %}
{% block body %}

<div class="container-fluid">
<!--Cards de reporte-->
     <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800"></h1>
                        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                                class="fas fa-download fa-sm text-white-50"></i> Nuevo reporte</a>
                    </div>
<!-- Content Row -->
                    <div class="row">

                        <!-- Card de Numero de pacientes -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-primary shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                                <a href="{% url 'pacientes:listaPaciente' %}">Pacientes Registrados</a> </div>
                                            <div class="h5 mb-0 font-weight-bold text-gray-800"></div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="fas fa-users fa-2x text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Card de ingresos de la clinica -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-success shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                                Ingresos  - {{MesACtual}}</div>
                                            <div class="h5 mb-0 font-weight-bold text-gray-800"></div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Citas Pendientes -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-info shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Citas pendientes hasta hoy 
                                            </div>
                                            <div class="row no-gutters align-items-center">
                                                <div class="col-auto">
                                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800"></div>
                                                </div>
                                                <div class="col">
                                                    <div class="progress progress-sm mr-2">
                                                        <div class="progress-bar bg-info" role="progressbar"
                                                            style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                                            aria-valuemax="100"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Card de productos -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-warning shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                                Total de productos</div>
                                            <div class="h5 mb-0 font-weight-bold text-gray-800">45</div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="fas fa-box fa-2x text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


    <!-- Content Row --> 
<!--Cards de reporte end-->
<!--Graficos-->
    <!-- Content Row -->

                    <div class="row">

                        <!-- Grafico Mensual de Ingresos -->
                        <div class="col-xl-8 col-lg-7">
                            <div class="card shadow mb-4">
                                <!-- Card Header - Dropdown -->
                                <div
                                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                    <h6 class="m-0 font-weight-bold text-primary">Vista previa de los ingresos</h6>
                                    <div class="dropdown no-arrow">
                                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                        </a>
                                    
                                    </div>
                                </div>
                                <!-- Card Body -->
                                <div class="card-body">
                                    <div class="chart-area">
                                        <canvas id="myAreaChart"></canvas>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Grafico de Pacientes -->
                        <div class="col-xl-4 col-lg-5">
                            <div class="card shadow mb-4">
                                <!-- Card Header - Dropdown -->
                                <div
                                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                    <h6 class="m-0 font-weight-bold text-primary">Vista Previa de Pacientes</h6>
                                    <div class="dropdown no-arrow">
                                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                        </a>
                                       
                                    </div>
                                </div>
                                <!-- Card Body -->
                                <div class="card-body">
                                    <div class="chart-pie pt-4 pb-2">
                                        <canvas id="myPieChart"></canvas>
                                    </div>
                                    <div class="mt-4 text-center small">
                                        <span class="mr-2">
                                            <i class="fas fa-circle text-primary"></i> Atentidos
                                        </span>
                                        <span class="mr-2">
                                            <i class="fas fa-circle text-success"></i> Nuevos
                                        </span>
                                        <span class="mr-2">
                                            <i class="fas fa-circle text-info"></i> Pendientes
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
<!--Graficos end-->
</div>
{% endblock %}