BaseApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

OralExpertsSGCD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BaseApp.urls')),                     # index - homepage - dashboard principal
    path('pacientes/', include('PacientesApp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PacientesApp/urls.py
from django.urls import path
from . import views

app_name = 'pacientes'
urlpatterns = [
    # path('', views.index, name='index'),           #añadirle una pag principal a sample.com/pacientes/
    path('', views.listaPaciente, name='listaPaciente'),
    path('nuevo/', views.nuevoPaciente, name='nuevoPaciente'),
    path('<int:item_id>/perfil/', views.perfilPaciente, name='perfilPaciente'),

    # Especialidades
    path('<int:item_id>/odontogeneral', views.listaOdontogeneral, name='listaOdontogeneral'),
    path('<int:item_id>/odontogeneral/nuevo', views.nuevoOdontogeneral, name='nuevoOdontogeneral'),

    path('<int:item_id>/odontopediatria', views.listaOdontopediatria, name='listaOdontopedriatria'),
    path('<int:item_id>/odontopediatria/nuevo', views.nuevoOdontopediatria, name='nuevoOdontopediatria'),

    path('<int:item_id>/endodoncia', views.listaEndodoncia, name='listaEndodoncia'),
    path('<int:item_id>/endodoncia/nuevo', views.nuevoEndodoncia, name='nuevoEndodoncia'),

    path('<int:item_id>/ortodoncia', views.listaOrtodoncia, name='listaOrtodoncia'),
    path('<int:item_id>/ortodoncia/nuevo', views.nuevoOrtodoncia, name='nuevoOrtodoncia'),

    path('<int:item_id>/rehaboral', views.listaRehaboral, name='listaRehaboral'),
    path('<int:item_id>/rehaboral/nuevo', views.nuevoRehaboral, name='nuevoRehaboral'),

    # PlanDeTratamiento
    path('<int:item_id>/plantratamiento', views.planTratamiento, name='planTratamiento'),

    # pagos
    path('<int:item_id>/pagos', views.listaPagos, name='listaPagos'),
    path('<int:item_id>/pagos/nuevo', views.nuevoPago, name='nuevoPago'),

    # recetas
    path('<int:item_id>/recetas', views.listaRecetas, name='listaRecetas'),

    # imagenes
    path('<int:item_id>/imagenes', views.imagenes, name='imagenes'),

    # odontograma
    path('<int:item_id>/odontograma', views.odontograma, name='odontograma'),
    path('<int:item_id>/odontograma/actualizar', views.actualizaOdontograma, name='actualizaOdontograma')
]

templates/pacientes/ListEndodoncia.html
{% extends 'pacientes/base.html' %}

{% block titulo %}|Endodoncia{% endblock %}

{% block imagenes-activo %}active{% endblock %}

{% block body %}
<!--modal eliminar-->
<div class="modal fade" id="modal-eliminar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Advertencia</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ¿Desea eliminar la consulta?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary">Eliminar</button>
      </div>
    </div>
  </div>
</div>
<!--modal eliminar end-->
<div class="container-fluid">
<!--Container-fluid -->
<h1 class="h3 mb-2 text-gray-800">Paciente: {{ itemPaciente }}</h1><br>
                     <a href="{% url 'pacientes:nuevoEndodoncia' itemPaciente.id %}" class="btn btn-info btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-plus"></i>
                        </span>
                        <span class="text">Nueva consulta</span>
                    </a><br><br>
<!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Lista de endodoncias</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead class="text-center">
                                        <tr>
                                             <th>N°</th>
                                            <th>Fecha</th>
                                            <th>Diagnóstico</th>
                                            <th>Acción</th>
                                        </tr>
                                    </thead>
                                    <tfoot class="text-center">
                                        <tr>
                                            <th>N°</th>
                                            <th>Fecha</th>
                                            <th>Diagnóstico</th>
                                            <th>Acción</th>
                                        </tr>
                                    </tfoot>
                                    <tbody class="text-center">
                                     {% for item in Endodoncia %}   
                                        <tr>
                                            <td>{{ item.pk }}</td>
                                            <td>{{ item.dEndoFecha  }}</td>
                                            <td>{{ item.tEndoDiagnostico }}</td>
                                            <td>
                                                <a href="{% url 'endodoncia' %}" class="btn btn-info btn-icon-split">
                                                     <span class="icon text-white-50">
                                                        <i class="fas fa-info-circle"></i>
                                                    </span>
                                                 </a>
                                                 <a href="#" class="btn btn-primary btn-icon-split">
                                                    <span class="icon text-white-50">
                                                         <i class="fas fa-print"></i>
                                                     </span>
                                                 </a>
                                                 <a href="#" class="btn btn-danger btn-icon-split" data-toggle="modal" data-target="#modal-eliminar">
                                                    <span class="icon text-white-50">
                                                        <i class="fas fa-trash"></i>
                                                     </span>
                                                 </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
<!-- /.container-fluid -->
{% endblock %}

templates/pacientes/ListOdontGeneral.html
{% extends 'pacientes/base.html' %}

{% block titulo %}|Odontología General{% endblock %}

{% block imagenes-activo %}active{% endblock %}

{% block body %}
<!--modal eliminar-->
<div class="modal fade" id="modal-eliminar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Advertencia</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ¿Desea eliminar la consulta?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary">Eliminar</button>
      </div>
    </div>
  </div>
</div>
<!--modal eliminar end-->
<div class="container-fluid">
<!--Container-fluid -->
<h1 class="h3 mb-2 text-gray-800">Paciente: {{ itemPaciente }}</h1><br>
                     <a href="{% url 'pacientes:nuevoOdontogeneral' itemPaciente.id %}" class="btn btn-info btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-plus"></i>
                        </span>
                        <span class="text">Nueva consulta</span>
                    </a><br><br>
<!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Lista de odontolgía general</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead class="text-center">
                                        <tr>
                                             <th>N°</th>
                                            <th>Fecha</th>
                                            <th>Motivo de consulta</th>
                                            <th>Acción</th>
                                        </tr>
                                    </thead>
                                    <tfoot class="text-center">
                                        <tr>
                                            <th>N°</th>
                                            <th>Fecha</th>
                                            <th>Motivo de consulta</th>
                                            <th>Acción</th>
                                        </tr>
                                    </tfoot>
                                    <tbody class="text-center">
                                    {% for item in itemsOdontoGeneral  %}
                                        <tr>    
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ item.dOdontGeneralFecha }}</td>
                                            <td>{{ item.tMotivoConsulta }}</td>
                                            <td>
                                                <a href="" class="btn btn-info btn-icon-split">
                                                     <span class="icon text-white-50">
                                                        <i class="fas fa-info-circle"></i>
                                                    </span>
                                                 </a>
                                                 <a href="#" class="btn btn-primary btn-icon-split">
                                                    <span class="icon text-white-50">
                                                         <i class="fas fa-print"></i>
                                                     </span>
                                                 </a>
                                                 <a href="#" class="btn btn-danger btn-icon-split" data-toggle="modal" data-target="#modal-eliminar">
                                                    <span class="icon text-white-50">
                                                        <i class="fas fa-trash"></i>
                                                     </span>
                                                 </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
<!-- /.container-fluid -->
{% endblock %}

templates/pacientes/ListOrtodoncia.html
{% extends 'pacientes/base.html' %}

{% block titulo %}|Ortodoncia {% endblock %}

{% block imagenes-activo %}active{% endblock %}

{% block body %}
<!--modal eliminar-->
<div class="modal fade" id="modal-eliminar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Advertencia</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ¿Desea eliminar la consulta?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary">Eliminar</button>
      </div>
    </div>
  </div>
</div>
<!--modal eliminar end-->
<div class="container-fluid">
<!--Container-fluid -->
<h1 class="h3 mb-2 text-gray-800">Paciente: {{ itemPaciente }}</h1><br>
                     <a href="{% url 'pacientes:nuevoOrtodoncia' itemPaciente.id  %}" class="btn btn-info btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-plus"></i>
                        </span>
                        <span class="text">Nueva consulta</span>
                    </a><br><br>
<!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Lista de Ortodoncias</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead class="text-center">
                                        <tr>
                                             <th>N°</th>
                                            <th>Fecha</th>
                                            <th>Acción</th>
                                        </tr>
                                    </thead>
                                    <tfoot class="text-center">
                                        <tr>
                                            <th>N°</th>
                                            <th>Fecha</th>
                                            <th>Acción</th>
                                        </tr>
                                    </tfoot>
                                    <tbody class="text-center">
                                    {% for item in itemsOrtodoncia %}
                                        <tr>
                                            <td>{{ item.pk }}</td>
                                            <td>{{ item.dOrtoFecha }}</td>
                                            <td>
                                                <a href="{% url 'pacientes:listaOrtodoncia' itemPaciente.id %}" class="btn btn-info btn-icon-split">
                                                     <span class="icon text-white-50">
                                                        <i class="fas fa-info-circle"></i>
                                                    </span>
                                                 </a>
                                                 <a href="#" class="btn btn-primary btn-icon-split">
                                                    <span class="icon text-white-50">
                                                         <i class="fas fa-print"></i>
                                                     </span>
                                                 </a>
                                                 <a href="#" class="btn btn-danger btn-icon-split" data-toggle="modal" data-target="#modal-eliminar">
                                                    <span class="icon text-white-50">
                                                        <i class="fas fa-trash"></i>
                                                     </span>
                                                 </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
<!-- /.container-fluid -->
{% endblock %}

templates/pacientes/NewOdontGeneral.html
{% extends 'pacientes/base.html' %}


{% block titulo %}Odontología General{% endblock %}

{% block especialidades-activo %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800">Paciente: {{ itemPaciente  }}</h1><br>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Ondontolgía General</h6>
        </div>
        <div class="card-body">
            <form class="user" method="POST">
                {% csrf_token %}
                <div class="form-group">

                    <h3>Aspectos Generales </h3>
                    <br>
                    <div class="form-group">
                        <div class="form-group">
                            <label>Fecha de la consulta</label>
                            {{ frmOdGeneral.dOdontGeneralFecha }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md">
                            <label>Motivo de Consulta</label>
                            {{ frmOdGeneral.tMotivoConsulta }}
                        </div>
                        <div class="form-group col-md">
                            <label>Enfermedad Actual</label>
                            {{ frmOdGeneral.cEnfermedadActual }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md">
                            <label>Medicina Actual</label>
                            {{ frmOdGeneral.tMedicaActual }}
                        </div>
                        <div class="form-group col-md">
                            <label>Tiempo de la Enfermedad</label>
                            {{ frmOdGeneral.cTiempoEnfermedad }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md">
                            <label>Sintomas</label>
                            {{ frmOdGeneral.cSignosSintomas }}
                        </div>
                        <div class="form-group col-md">
                            <label>Relato Cronológico</label>
                            {{ frmOdGeneral.tRelatoCrono }}
                        </div>
                    </div>
                    <br>
                    <h3>Antecedentes Cronológicos </h3>
                    <br>
                    <div class="form-row">
                        <div class="form-group col-md">
                            <label>Antecedentes Familiares</label>
                            {{ frmOdGeneral.tAnteceFamiliar }}
                        </div>
                        <div class="form-group col-md">
                            <label>Antecedentes Personales</label>
                            {{ frmOdGeneral.tAntecePersonal }}
                        </div>
                    </div>
                    <br>
                    <h3>Examen actual</h3>
                    <br>
                    <div class="form-row">
                        <div class="form-group col-md">
                            <label>Examen General</label>
                            {{ frmOdGeneral.tExamenGeneral }}
                        </div>
                        <div class="form-group col-md">
                            <label>Examen Estomatológico</label>
                            {{ frmOdGeneral.tExamenOdontEstoma }}
                        </div>
                    </div>
                    <br>
                    <h3>Tipos de Diagnósticos</h3>
                    <br>
                    <div class="form-row">
                        <div class="form-group col-md">
                            <label>Diagnóstico Definitivo</label>
                            {{ frmOdGeneral.tDiagDefinitivo }}
                        </div>
                        <div class="form-group col-md">
                            <label>Diagnóstico Presuntivo</label>
                            {{ frmOdGeneral.tDiagPresuntivo }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md">
                            <label>Plan de Tratamiento</label>
                            {{ frmOdGeneral.tPlanTratamiento }}
                        </div>
                        <div class="form-group col-md">
                            <label>Recomendaciones</label>
                            {{ frmOdGeneral.tRecomendacion }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md">
                            <label>Alta del Paciente</label>
                            {{ frmOdGeneral.tAlta }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/pacientes/NewPaciente.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Nuevo Usuario{% endblock %}

{% block registrar-activo %}active{% endblock %}

{% block body %}
<style>
    @media (min-width: 1200px) {
        .container,
        .container-sm,
        .container-md,
        .container-lg,
        .container-xl {
            max-width: 1340px;
        }
    }
</style>
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
    
            reader.onload = function (e) {
                $('#myimage').attr('src', e.target.result);
            };
    
            reader.readAsDataURL(input.files[0]);
        }
    }
    </script>
<div class="container-fluid">
    <a href="{% url 'pacientes:listaPaciente' %}" class="btn btn-info btn-icon-split">
        <span class="icon text-white-50">
            <i class="fas fa-eye"></i>
        </span>
        <span class="text">Lista de pacientes</span>
    </a><br><br>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Nuevo Paciente</h6>
        </div>
        <div class="card-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-auto">
                        <div class="form-group col-md">
                            <form class="user" enctype="multipart/form-data" method="POST">
                                {% csrf_token %}
                                <center>
                                    <img class="rounded-circle border border-primary" alt=":)"
                                    id="myimage" src="{% static 'img/perfil_defecto.png' %}" width="150px" height="150px"
                                        data-holder-rendered="true">
                                </center><br>
                                

                                <div class="input-group mb-3">
                                    <div class="custom-file">
                                        {{ frmPaciente.iPacImg }}
                                        <label class="custom-file-label" for="inputGroupFile01">Elegir imagen...</label>
                                    </div>
                                </div>
                        </div>
                    </div>
                    <div class="col-md">

                        <div class="form-group">
                            <div class="form-group">
                                <label>Nombres y apellidos</label>
                                {{ frmPaciente.cPacNombres }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-8">
                                <label>Correo electrónico</label>
                                {{ frmPaciente.cPacEmail }}
                            </div>
                            <div class="form-group col-md-4">
                                <label>DNI</label>
                                {{ frmPaciente.nPacDni }}
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>Dirección</label>
                                {{ frmPaciente.cPacDireccion }}
                            </div>
                            <div class="form-group col-md-6">
                                <label>Código postal</label>
                                {{ frmPaciente.nPacCodPostal }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label>Ciudad de nacimiento</label>
                                {{ frmPaciente.cPacCiudadNacimiento }}
                            </div>
                            <div class="form-group col-md-4">
                                <label>Fecha de nacimiento</label>
                                {{ frmPaciente.dPacFecNacimiento }}
                            </div>
                            <div class="form-group col-md-4">
                                <label>Sexo</label>
                                {{ frmPaciente.cPacSexo }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>Ocupación</label>
                                {{ frmPaciente.cPacOcupacion }}
                            </div>
                            <div class="form-group col-md-4">
                                <label>Estado civil</label>
                                {{ frmPaciente.cPacEstadoCivil }}
                            </div>
                            <div class="form-group col-md-2">
                                <label for="inputZip">Teléfono/celular</label>
                                {{ frmPaciente.nPacCelTlf }}
                            </div>
                        </div>
                        <div class="form-row">
                            <!-- <div class="form-group col-md-6">
                                            <label>Grado de estudios</label>
                                            {{ frmPaciente.cPacNombres }}
                                            </div> -->
                            <div class="form-group col-md-12">
                                <label>Alergias</label>
                                {{ frmPaciente.cPacAlergia }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-8">
                                <label>Nombres y apellidos del acompañante</label>
                                {{ frmPaciente.cNombresApoderado }}
                            </div>
                            <div class="form-group col-md-4">
                                <label>Teléfono del acompañante</label>
                                {{ frmPaciente.nTelfApoderado }}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-user btn-block">Guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}